-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 21:37:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto2Bases1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto2Bases1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto2Bases1` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto2Bases1` ;

-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Rol_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Rol_Usuario` (
  `Rol_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Rol_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Usuario` (
  `Usuario` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(250) NULL,
  `Telefono` VARCHAR(15) NULL,
  `Correo` VARCHAR(100) NULL,
  `Password` VARCHAR(250) NULL,
  `Rol_Usuario` INT NOT NULL,
  PRIMARY KEY (`Usuario`),
  INDEX `FK_Rol_Usuario` (`Rol_Usuario` ASC) VISIBLE,
  CONSTRAINT `FK_Rol_Usuario`
    FOREIGN KEY (`Rol_Usuario`)
    REFERENCES `Proyecto2Bases1`.`Rol_Usuario` (`Rol_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Caja` (
  `Caja` INT NOT NULL,
  `Monto` INT NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`Caja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Abrir_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Abrir_Caja` (
  `Fecha_Hora` DATETIME NOT NULL,
  `Monto` INT NOT NULL,
  `Usuario` INT NOT NULL,
  `Caja` INT NOT NULL,
  INDEX `FK_Usuario` (`Usuario` ASC) VISIBLE,
  INDEX `FK_Caja` (`Caja` ASC) VISIBLE,
  PRIMARY KEY (`Usuario`, `Caja`),
  CONSTRAINT `fk_Abrir_Caja_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `Proyecto2Bases1`.`Usuario` (`Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Abrir_Caja_Caja1`
    FOREIGN KEY (`Caja`)
    REFERENCES `Proyecto2Bases1`.`Caja` (`Caja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Cerrar_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Cerrar_Caja` (
  `Fecha_Hora` DATETIME NOT NULL,
  `Monto_Numero` INT NOT NULL,
  `Monto_Letras` VARCHAR(250) NULL,
  `Observacion` VARCHAR(250) NULL,
  `Usuario_Usuario` INT NOT NULL,
  `Caja_Caja` INT NOT NULL,
  INDEX `FK_Usuario` (`Usuario_Usuario` ASC) VISIBLE,
  INDEX `FK_Caja` (`Caja_Caja` ASC) VISIBLE,
  PRIMARY KEY (`Usuario_Usuario`, `Caja_Caja`),
  CONSTRAINT `fk_Cerrar_Caja_Usuario1`
    FOREIGN KEY (`Usuario_Usuario`)
    REFERENCES `Proyecto2Bases1`.`Usuario` (`Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cerrar_Caja_Caja1`
    FOREIGN KEY (`Caja_Caja`)
    REFERENCES `Proyecto2Bases1`.`Caja` (`Caja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Movimiento` (
  `Movimiento` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Hora` DATETIME NOT NULL,
  `Descripcion` VARCHAR(250) NULL,
  `Monto` INT NOT NULL,
  `Saldo_Caja` INT NOT NULL,
  `Usuario` INT NOT NULL,
  `Caja` INT NOT NULL,
  PRIMARY KEY (`Movimiento`, `Usuario`),
  INDEX `FK_Caja_Abierta` (`Usuario` ASC, `Caja` ASC) VISIBLE,
  CONSTRAINT `fk_Movimiento_Abrir_Caja1`
    FOREIGN KEY (`Usuario` , `Caja`)
    REFERENCES `Proyecto2Bases1`.`Abrir_Caja` (`Usuario` , `Caja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Tipo_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Tipo_Pago` (
  `Tipo_Pago` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tipo_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Egreso` (
  `Egreso` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Hora` DATETIME NOT NULL,
  `Monto` INT NULL,
  `No_Recibo` VARCHAR(45) NOT NULL,
  `Tipo_Pago` INT NOT NULL,
  `Usuario` INT NOT NULL,
  `Caja` INT NOT NULL,
  PRIMARY KEY (`Egreso`),
  INDEX `FK_Tipo_Pago` (`Tipo_Pago` ASC) VISIBLE,
  INDEX `FK_Caja_Abierta` (`Usuario` ASC, `Caja` ASC) VISIBLE,
  CONSTRAINT `fk_Egreso_Tipo_Pago1`
    FOREIGN KEY (`Tipo_Pago`)
    REFERENCES `Proyecto2Bases1`.`Tipo_Pago` (`Tipo_Pago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Egreso_Abrir_Caja1`
    FOREIGN KEY (`Usuario` , `Caja`)
    REFERENCES `Proyecto2Bases1`.`Abrir_Caja` (`Usuario` , `Caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Cliente` (
  `DPI` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `NIT` INT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Correo` VARCHAR(100) NULL,
  PRIMARY KEY (`DPI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Factura` (
  `Factura` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Hora` DATETIME NOT NULL,
  `Cliente` INT NOT NULL,
  `NIT` INT NOT NULL,
  `Total` INT NOT NULL,
  `IVA_Venta` INT NOT NULL,
  PRIMARY KEY (`Factura`, `Cliente`),
  INDEX `FK_Cliente` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Proyecto2Bases1`.`Cliente` (`DPI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Venta` (
  `Venta` INT NOT NULL AUTO_INCREMENT,
  `NIT` INT NOT NULL,
  `Nombre_Cliente` VARCHAR(100) NOT NULL,
  `IVA` INT NOT NULL,
  `Monto_Pagado` INT NOT NULL,
  `Usuario` INT NOT NULL,
  `Caja` INT NOT NULL,
  `Factura` INT NOT NULL,
  PRIMARY KEY (`Venta`, `Factura`),
  INDEX `FK_Caja_Abierta` (`Usuario` ASC, `Caja` ASC) VISIBLE,
  INDEX `FK_Factura` (`Factura` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Abrir_Caja1`
    FOREIGN KEY (`Usuario` , `Caja`)
    REFERENCES `Proyecto2Bases1`.`Abrir_Caja` (`Usuario` , `Caja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venta_Factura1`
    FOREIGN KEY (`Factura`)
    REFERENCES `Proyecto2Bases1`.`Factura` (`Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Tipo_Transacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Tipo_Transacion` (
  `Tipo_Transacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tipo_Transacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Estado_Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Estado_Cuenta` (
  `Es tado_Cuenta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Es tado_Cuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Cuenta` (
  `Cuenta` INT NOT NULL AUTO_INCREMENT,
  `No_factura` INT NOT NULL,
  `Fecha_Emision` DATETIME NOT NULL,
  `Total_Factura` INT NOT NULL,
  `Saldo_Factura` INT NOT NULL,
  `Cliente` INT NOT NULL,
  `Estado_Cuenta` INT NOT NULL,
  PRIMARY KEY (`Cuenta`),
  INDEX `FK_Cliente` (`Cliente` ASC) VISIBLE,
  INDEX `FK_Estado_Cuenta` (`Estado_Cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Proyecto2Bases1`.`Cliente` (`DPI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cuenta_Estado_Cuenta1`
    FOREIGN KEY (`Estado_Cuenta`)
    REFERENCES `Proyecto2Bases1`.`Estado_Cuenta` (`Es tado_Cuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Transacion_Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Transacion_Cuenta` (
  `Transacion_Cuenta` INT NOT NULL AUTO_INCREMENT,
  `Monto` INT NOT NULL,
  `Cuenta` INT NOT NULL,
  `Tipo_Tranzacion` INT NOT NULL,
  PRIMARY KEY (`Transacion_Cuenta`),
  INDEX `FK_Cuenta` (`Cuenta` ASC) VISIBLE,
  INDEX `FK_Tipo_Tranzacion` (`Tipo_Tranzacion` ASC) VISIBLE,
  CONSTRAINT `fk_Tranzacion_Cuenta_Cuenta1`
    FOREIGN KEY (`Cuenta`)
    REFERENCES `Proyecto2Bases1`.`Cuenta` (`Cuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tranzacion_Cuenta_Tipo_Cuenta1`
    FOREIGN KEY (`Tipo_Tranzacion`)
    REFERENCES `Proyecto2Bases1`.`Tipo_Transacion` (`Tipo_Transacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Tipo_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Tipo_Categoria` (
  `Tipo_Categoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tipo_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Producto` (
  `Producto` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Precio` INT NOT NULL,
  PRIMARY KEY (`Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Categoria` (
  `Producto` INT NOT NULL,
  `Tipo_Categoria` INT NOT NULL,
  INDEX `FK_Producto` (`Producto` ASC) VISIBLE,
  INDEX `FK_Tipo_Categoria` (`Tipo_Categoria` ASC) VISIBLE,
  PRIMARY KEY (`Producto`, `Tipo_Categoria`),
  CONSTRAINT `fk_Categoria_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `Proyecto2Bases1`.`Producto` (`Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Categoria_Tipo_Categoria1`
    FOREIGN KEY (`Tipo_Categoria`)
    REFERENCES `Proyecto2Bases1`.`Tipo_Categoria` (`Tipo_Categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Descuento` (
  `Descuento` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Inicio` DATETIME NOT NULL,
  `Fecha_Fin` DATETIME NULL,
  `Porcentaje_Descuento` INT NOT NULL,
  `Producto` INT NOT NULL,
  PRIMARY KEY (`Descuento`),
  INDEX `FK_Producto` (`Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Descuento_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `Proyecto2Bases1`.`Producto` (`Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Inventario` (
  `Inventario` INT NOT NULL AUTO_INCREMENT,
  `Unidades_Disponibles` INT NOT NULL,
  `Producto` INT NOT NULL,
  PRIMARY KEY (`Inventario`, `Producto`),
  INDEX `FK_Producto` (`Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `Proyecto2Bases1`.`Producto` (`Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Proveedor` (
  `Proveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(250) NOT NULL,
  `Correo` VARCHAR(100) NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Compra` (
  `Compra` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Precio_Unitario` INT NOT NULL,
  `Valor_Compra` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `No_Factura` INT NOT NULL,
  `Producto` INT NOT NULL,
  `Proveedor` INT NOT NULL,
  `Usuario` INT NOT NULL,
  PRIMARY KEY (`Compra`),
  INDEX `FK_Producto` (`Producto` ASC) VISIBLE,
  INDEX `FK_Proveedor` (`Proveedor` ASC) VISIBLE,
  INDEX `FK_Usuario` (`Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `Proyecto2Bases1`.`Producto` (`Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `Proyecto2Bases1`.`Proveedor` (`Proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Compra_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `Proyecto2Bases1`.`Usuario` (`Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Detalle` (
  `Factura` INT NOT NULL,
  `Producto` INT NOT NULL,
  `Cliente` INT NOT NULL,
  `Precio_Unidad` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  INDEX `FK_Factura` (`Factura` ASC, `Cliente` ASC) VISIBLE,
  INDEX `FK_Producto` (`Producto` ASC) VISIBLE,
  PRIMARY KEY (`Factura`, `Producto`),
  CONSTRAINT `fk_Detalle_Factura1`
    FOREIGN KEY (`Factura` , `Cliente`)
    REFERENCES `Proyecto2Bases1`.`Factura` (`Factura` , `Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Detalle_Producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `Proyecto2Bases1`.`Producto` (`Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2Bases1`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2Bases1`.`Log` (
  `Log` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Hora` DATETIME NOT NULL,
  `Descripcion` VARCHAR(250) NULL,
  `Monto_Movimiento` INT NULL,
  `Movimiento` INT NOT NULL,
  `Usuario` INT NOT NULL,
  PRIMARY KEY (`Log`, `Movimiento`, `Usuario`),
  INDEX `FK_Movimiento` (`Movimiento` ASC, `Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Log_Movimiento1`
    FOREIGN KEY (`Movimiento` , `Usuario`)
    REFERENCES `Proyecto2Bases1`.`Movimiento` (`Movimiento` , `Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
