DELIMITER //
CREATE PROCEDURE AGREGAR_ROL_USUARIO(IN NOMBRE VARCHAR(45))
BEGIN
INSERT INTO Rol_Usuario(Nombre) values(NOMBRE);
END//

-- LOGIN
USE `proyecto2bases1`;
DROP procedure IF EXISTS `LOGIN_USUARIO`;

DELIMITER $$
USE `proyecto2bases1`$$
CREATE PROCEDURE `LOGIN_USUARIO` (IN ID INT,IN PASS VARCHAR(250))
BEGIN
SELECT * FROM usuario
WHERE usuario.Usuario = ID AND usuario.Password = PASS;
END$$
DELIMITER ;

